redis_uri = "redis://127.0.0.1:6379"
log_level = "info"

[database]
username = "postgres"
password = "postgres"
port = 5432
host = "localhost"
database_name = "aloha"

[application]
port = 0
host = "127.0.0.1"
base_url = "http://127.0.0.1"
hmac_secret = "super-long-and-secret-random-key-needed-to-verify-message-integrity"
